CREATE TABLE "account" (
	"accountId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(255),
	"password" VARCHAR(255),
	"fullName" VARCHAR(255),
	"avatar" TEXT NOT NULL,
	PRIMARY KEY("accountId")
);




CREATE TABLE "novel_info" (
	"novelId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"novelTitle" VARCHAR(255) UNIQUE,
	"novelDescription" TEXT,
	"createDate" TIMESTAMP,
	"author" VARCHAR(255),
	PRIMARY KEY("novelId")
);


CREATE INDEX "novel_info_index_0"
ON "novel_info" ();

CREATE TABLE "chapter" (
	"chapterId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"index" REAL,
	"chapterTitle" VARCHAR(255),
	"createDate" TIMESTAMP,
	"updateDate" TIMESTAMP,
	"chapterText" TEXT,
	"chapterStatusId" INTEGER,
	PRIMARY KEY("chapterId")
);




CREATE TABLE "chapter_status" (
	"chapterStatusId" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"chapterStatusCode" VARCHAR(255),
	"chapterStatusDescription" TEXT,
	PRIMARY KEY("chapterStatusId")
);




CREATE TABLE "novel_chapter" (
	"novelId" INTEGER NOT NULL,
	"chapterId" INTEGER,
	PRIMARY KEY("novelId", "chapterId")
);




CREATE TABLE "uploader" (
	"accountId" INTEGER NOT NULL,
	"novelId" INTEGER,
	PRIMARY KEY("accountId", "novelId")
);


CREATE INDEX "uploader_index_0"
ON "uploader" ();
ALTER TABLE "account"
ADD FOREIGN KEY("accountId") REFERENCES "uploader"("accountId")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "uploader"
ADD FOREIGN KEY("novelId") REFERENCES "novel_info"("novelId")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "novel_info"
ADD FOREIGN KEY("novelId") REFERENCES "novel_chapter"("novelId")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "chapter"
ADD FOREIGN KEY("chapterId") REFERENCES "novel_chapter"("chapterId")
ON UPDATE NO ACTION ON DELETE NO ACTION;